version: '0.9'
services:
  db:
    image: 'postgres:14'
    environment:
      POSTGRES_USER: '${DB_USER}'
      POSTGRES_PASSWORD: '${DB_PASSWORD}'
      POSTGRES_DB: '${DB_NAME}'
    ports:
      - '5432:5432'
    volumes:
      - './db:/var/lib/postgresql/data'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "${DB_USER}"]

  airflow:
    build: ./airflow_container
    volumes: 
      - ./dags/:/airflow/dags/
      - ./airflow_db/:/airflow/airflow_db/
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: 'user@user.com'
      PGADMIN_DEFAULT_PASSWORD: 'user'
    ports:
      - '5050:80'
    volumes:
      - './pg_admin_folder/:/var/lib/pgadmin'
    depends_on:
      db:
        condition: service_healthy